"""initial database migration

Revision ID: 70f7c9ed4e38
Revises: 
Create Date: 2020-09-12 03:52:06.467521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f7c9ed4e38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logger', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('msg', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
